#!/bin/sh

# Installer script to set up symlinks for configuration files.
# Assumes it is being run as `./install <path>`, i.e. from the directory
# it lives in.

conf=$(dirname "$0")
conf=${conf-.}
cd $conf
conf=$(pwd -P)

home=${1:-$HOME}

echo "Installing config files from $conf into $home..."

function safe_link {
  target=$2
  if [ -z "$target" ]; then
    target=".$1"
  fi
  target="$home/$target"
  source="$conf/$1"
  if [ -h "$target" -a "$(readlink $target)" = "$source" ]; then
    # it's already there
    :
  elif [ -s "$target" ]; then
    echo "Cannot symlink "$source" -> "$target": file exists." >&2
  else
    ln -s "$source" "$target"
  fi
}

safe_link Xmodmap
safe_link Xdefaults
safe_link tmux.conf
safe_link bashrc
safe_link gitconfig
safe_link gitignore_global
safe_link gtkrc-2.0
safe_link aspell.en.pws

# Link everything in the bash directory
cd bash
mkdir -p $home/.bash.d
for a in *.sh; do
  safe_link bash/$a .bash.d/$a
done

# Unlink everything in the disabled directory
if [ -d disabled ]; then
  cd disabled
  for a in *.sh; do
    target="$home/.bash.d/$a"
    if [ -h $target -a "$(readlink $target)" = "$conf/bash/$a" ]; then
      rm -f $target
    elif [ -s "$target" ]; then
      echo "Refusing to delete non-symlink $target even though disabled."
    fi
  done
  cd ..
fi
cd ..

# Make bash completion dir so somebody doesn't complain
mkdir -p $home/.bash.d/completion

# Link all the emacs files
cd emacs
mkdir -p $home/.emacs.d
for a in *.el; do
  safe_link emacs/$a .emacs.d/$a
done

# Install the tmux-256color terminfo config
$conf/gen/tmux
