#!/bin/sh

# I like to use aptitude for installing, since it has better search
# and keeps better history of what was requested vs what was a dep.
sudo apt-get install aptitude

# We need xinput for remapping mouse scroll direction and caps lock.
sudo aptitude install xinput awesome xterm

# Generate an SSH key.
ssh-keygen -t rsa -b 4096 -C sdh@google.com
eval $(ssh-agent -s)
ssh-add ~/.ssh/id_rsa

# Need to install the key into github
echo "Please paste the following key into github:"
echo "================================================================"
cat ~/.ssh/id_rsa.pub
echo "================================================================"
echo "Press enter when done."
read unused

# Download config repo
git clone git@github.com:shicks/config

# Set up awesome as the default window manager (now version 4.0 - new configs)
#   - nothing seems to work!
#   - greeter-show-manual-login -> set to false to autofill?
#   - TODO - use run-parts to allow multiple configs in separate files
cat > ~/.xsessionrc <<EOF
~/fix-riose-screen
EOF
sudo tee /var/lib/AccountsService/users/sdh > /dev/null <<EOF
[User]
Language=
XSession=awesome
EOF

# Install alacritty
(
  mkdir -p ~/local/{opt,bin}
  cd ~/local/opt
  # Need rust and a few other prereqs
  curl https://sh.rustup.rs -sSf | sh
  rustup override set stable
  rustup update stable
  sudo aptitude install cmake libfreetype6-dev libfontconfig1-dev xclip
  git clone https://github.com/jwilm/alacritty.git
  cd alacritty
  cargo build --release
  ln -s ~/local/opt/alacritty/target/release/alacritty ~/local/bin/
)

# NOTE: Also need ~/local/bin in the path (~/bin is already there).
ln -s ~/local/bin ~/bin

# .gitconfig.d: install files copies templates from /usr/share/git-core
# Copy over post-rebase-tree and other hooks in gitconfig directory
mkdir -p ~/.gitconfig.d/templates/hooks
cp ~/dors/dot-gitconfig.d/templates/hooks/{post-rebase-tree,post-commit,pre-rebase} \
    ~/.gitconfig.d/templates/hooks/

# Install monofur-powerline font
~/config/install fonts

# TODO - install alacritty (note: update-alternatives for x-terminal-emulator??)
# TODO - rebase tmux changes, push upstream?!?

# Emacs - add melpa
#      (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
#   -- packages: lua-mode, many others (get list from dors)
